# ====================================
# GLOBAL COMPUTED VALUES
# ====================================
max_period: ${globals:max_period}

# ====================================
# OUTPUT CONFIGURATION
# ====================================
n_top_funds_output: 5

# ====================================
# INVESTOR PROFILES
# ====================================
investor_profiles:
  conservative:
    liquidity: 0.05       
    risk_reward: 0.10         
    volatility: 0.30         
    concentration: 0.10       
    asset_diversification: 0.10  
    fund_age: 0.20       
    credit_quality: 0.15      
    allowed_fund_subtypes:
      - Renda Fixa Simples
      - Renda Fixa Indexados
      - Renda Fixa Duração Baixa Soberano

  moderate:
    liquidity: 0.13           
    risk_reward: 0.35         
    volatility: 0.13          
    concentration: 0.08       
    asset_diversification: 0.13  
    fund_age: 0.08            
    credit_quality: 0.10   
  
  aggressive:
    liquidity: 0.08           
    risk_reward: 0.50         
    volatility: 0.15          
    concentration: 0.05       
    asset_diversification: 0.08  
    fund_age: 0.07            
    credit_quality: 0.07     

  speculator:
    liquidity: 0.03           
    risk_reward: 0.60         
    volatility: 0.20         
    concentration: 0.03       
    asset_diversification: 0.03  
    fund_age: 0.03            
    credit_quality: 0.08
    target_investor_profile:
    - Profissional
    #- Qualificado
    #- Geral
    #- ND

# ====================================
# CREDIT RATING
# ====================================
# Ratings not in order list are treated as unrated (null score)
# Ignored data quality issues: ALTO, F, Pend (pending)
credit_rating:
  order: &credit_rating_order
    - AAA+
    - AAA
    - BRAAA
    - AAA(BR
    - Aaa.br
    - BRAA+
    - AA+
    - AA
    - AA(BRA
    - AA-(BR
    - AA-
    - A+(BRA
    - A
    - A-
    - BBB+
    - BAA2.B
    - BBB-(B
    - BRBBB-
    - Ba1
    - Ba2
    - BA2.BR
    - BB-
  weight_investment_grade: 0.6
  weight_avg_rating_score: 0.4
  credit_rating_investment_grade_threshold: BRBBB-

# ====================================
# GUARDRAILS
# ====================================
guardrails:
  min_offer_per_issuer:
    active: true
    params: 
      min_offer_count: 5
  
  min_threshold_sharpe_12m: 
    active: true
    params: 
      min_sharpe_12m: 0.0

  min_threshold_sharpe_3m: 
    active: false
    params: 
      min_sharpe_3m: 0.0

  no_funds_wo_manager:
    active: false
  
  include_only_active_funds:
    active: true

  no_extreme_returns:
    active: true
    params:
      max_abs_monthly_return: 1.0

# ====================================
# DATA SCOPE
# ====================================
num_period_months: null # all available months
min_data_period_per_fund: 3
remove_funds_w_negative_cvm_pl_values: true # 24 funds with negative NAV value in latest period (202509)

cvm_fi_fund_types:
 - CLASSES - FIF
 - FI  # previous classification
 
anbima_fi_fund_types:
 - Renda Fixa
 
anbima_accessability:
- Não Há Restrição
- Não há Restrição

# ====================================
# RISK & SCORING
# ====================================
risk_free_rate_annual: 0.1371  # CDI on 23/11

fund_age_cap_years: 30.0

normalization_lower_percentile: 0.05
normalization_upper_percentile: 0.95
use_log_volatility: true

# ====================================
# RAW DATA VALIDATION
# ====================================
# Pre-parsing validations run before pipeline execution via Kedro hook
# Runs BEFORE catalog.load() to fix known issues:
# << list here the known issues that are checked in the files >>
#
# Strategies per validation: fix | ignore
#   - fix: Repair data in-place (only where a fix method exists)
#   - ignore: Remove affected lines entirely
data_validation:
  enabled: true
  report_include_passed: false
  
  datasets:
    raw_cvm_monthly_fund_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    raw_cvm_blc_1_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    raw_cvm_blc_2_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    raw_cvm_blc_3_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    raw_cvm_blc_4_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    raw_cvm_blc_5_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    raw_cvm_blc_6_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    raw_cvm_blc_7_data:
      validations:
        check_redundant_quotes: fix
        check_malformed_quotes: fix
    
    ## ignored as it seems to not contain real instruments
    # raw_cvm_blc_8_data:
    #  validations:
    #    check_redundant_quotes: fix
    #    check_malformed_quotes: fix
    
# ====================================
# DATAFRAME VALIDATIONS
# ====================================
# Validations run after datasets are loaded (input of nodes) or saved (output of nodes)
# These validate DataFrame content and report issues (no fixes, just logging).
dataframe_validation:
  report_include_passed: false

input_validations:
  raw_cvm_monthly_fund_data:
    validations:
      validate_uniqueness:
        group_columns:
        - CNPJ_FUNDO
        - DT_COMPTC
        - VL_PATRIM_LIQ
      validate_bounds:
        value_column: VL_PATRIM_LIQ
        identifier_column: CNPJ_FUNDO
        lower_bound: 0
        upper_bound: null

  raw_cvm_blc_5_data:
    validations:
      validate_allowed_values:
        value_column: GRAU_RISCO
        allowed_values: *credit_rating_order
output_validations:
  pri_returns_per_fund:
    validations:
      validate_time_completeness:
        time_column: period
        group_column: cnpj
      validate_uniqueness:
        group_columns:
        - cnpj
        - period
  pri_nav_per_period:
    validations:
      validate_time_completeness:
        time_column: period
        group_column: cnpj
      validate_uniqueness:
        group_columns:
        - cnpj
        - period
  pri_instrument_prices:
    validations:
      validate_uniqueness:
        group_columns:
        - instrument_id
        - period